modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
isplayURL = "${homepage}"
authors = ["${mod_author}"]
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"


